name: Release

on:
  release:
    types: [published]
  push:
    branches: [workflow-release-test]

env:
  CARGO_TERM_COLOR: always
  RUST_MIN_STACK: 16777212

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, macos-latest, windows-latest]
        include:
          - platform: ubuntu-22.04
            artifact-path: ./target/release/sdl
            artifact-platform-name: linux-x64
            env-command: ">> $GITHUB_ENV"
          - platform: macos-latest
            artifact-path: ./target/release/sdl
            artifact-platform-name: macos-aarch64
            env-command: ">> $GITHUB_ENV"
          - platform: windows-latest
            artifact-path: ./target/release/sdl.exe
            artifact-platform-name: windows-x64
            env-command: "| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append"

    runs-on: ${{ matrix.platform }}

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update

      - uses: swatinem/rust-cache@v2

      - name: Build, get version
        run: |
          cargo run --release --bin sdl -- --help
          echo "SDL_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages | .[0].version')" ${{ matrix.env-command }}

      - name: Archive (Windows)
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          7z a -tzip -mm=Deflate sdl-${{ env.SDL_VERSION }}-${{ matrix.artifact-platform-name }}.zip ${{ matrix.artifact-path }}

      - name: Archive (Unix)
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          gzip -c ${{ matrix.artifact-path }} > sdl-${{ env.SDL_VERSION }}-${{ matrix.artifact-platform-name }}.gz
          
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sdl-${{ env.SDL_VERSION }}-${{ matrix.artifact-platform-name }}.zip
            sdl-${{ env.SDL_VERSION }}-${{ matrix.artifact-platform-name }}.gz
